baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'AkiraShougun'
theme = 'hugo-theme-stack'

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

[params]
  [[Params.Sidebar]]
    avatar = "/images/image.png"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

